#!/bin/bash
#
# anode
#
# chkconfig:   <3,4,5> <start> <stop>
# description: ANode deamon
#
# # BEGIN INIT INFO
# Provides:          anode
# Required-Start:
# Required-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: ANode
# Description:       ANode daemon
### END INIT INFO

ANODE_PATH=$(which anode)
ANODE_LOCK=/var/lock/subsys/anode
ANODE_FUNCTIONS=/etc/init.d/functions

if [ -f ${ANODE_FUNCTIONS} ]; then
  . ${ANODE_FUNCTIONS}
else
  function initlog {
    echo "$1" > /dev/null
    $2
  }
  function success {
    echo " $1"
  }
  function failure {
    echo " $1"
  }
  function killproc {
    echo "$1" > /dev/null
    kill $(cat ${ANODE_LOCK})
  }
fi

ANODE_OPTS=${ANODE_OPTS:-"-q"}
ANODE_LOG_FILE=${ANODE_LOG_FILE:-"/dev/null"}

start() {
  initlog -c "echo -n Starting anode: "
  if [ ! -f ${ANODE_LOCK} ]; then
    if [ "${ANODE_PATH}" == "" ]; then
      failure $"could not locate anode binary"
      exit 2
    fi
    mkdir -p $(dirname ${ANODE_PATH}) $(dirname ${ANODE_LOG_FILE})
    nohup ${ANODE_PATH} ${ANODE_OPTS} > ${ANODE_LOG_FILE} &
    if [ $? -eq 0 ]; then
      echo $! > ${ANODE_LOCK}
      success $"anode started"
    else
      failure $"anode failed to start"
      exit 1
    fi
  else
    failure $"anode already started"
    exit 1
  fi
}

stop() {
  initlog -c "echo -n Stopping anode: "
  if [ -f ${ANODE_LOCK} ]; then
    killproc ${ANODE_PATH} 2> /dev/null
    rm -f ${ANODE_LOCK}
    success $"anode stopped"
  else
    failure $"anode not started"
  fi
}

status() {
  initlog -c "echo -n Status anode: "
  if [ -f ${ANODE_LOCK} ]; then
    success $"anode started"
  else
    failure $"anode stopped"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0
