#!/bin/sh
# chkconfig:   <3,4,5> <start> <stop>
# description: ANode deamon
#
### BEGIN INIT INFO
# Provides:          anode
# Required-Start:    $weewx
# Required-Stop:     $weewx
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: ANode
# Description:       ANode daemon
### END INIT INFO

ANODE_PATH=$(which anode)
ANODE_LOCK=/var/lock/subsys/anode
ANODE_OPTS=${ANODE_OPTS:-""}
ANODE_ENV_FILE=${ANODE_ENV_FILE:-"/etc/bash.bashrc"}
ANODE_LOG_FILE=${ANODE_LOG_FILE:-"/var/log/anode.log"}

[ -f ${ANODE_ENV_FILE} ] && $(grep NETATMO ${ANODE_ENV_FILE})

log_head() {
  /bin/echo -n "$1"
}

log_tail_success() {
  /bin/echo "$1"
}

log_tail_failure() {
  /bin/echo "$1"
}

start() {
  log_head "Starting anode: "
  if [ ! -f ${ANODE_LOCK} ]; then
    if [ -z ${ANODE_PATH} ]; then
      log_tail_failure "could not locate anode binary"
    else
      mkdir -p $(dirname ${ANODE_PATH}) $(dirname ${ANODE_LOG_FILE})
      nohup ${ANODE_PATH} ${ANODE_OPTS} > ${ANODE_LOG_FILE} 2>&1 &
      if [ $? -eq 0 ]; then
        echo $! > ${ANODE_LOCK}
        log_tail_success "anode started"
      else
        log_tail_failure "anode failed to start"
      fi
    fi
  else
    log_tail_failure "anode already started"
  fi
}

stop() {
  log_head "Stopping anode: "
  if [ -f ${ANODE_LOCK} ]; then
    kill $(cat ${ANODE_LOCK}) 2> /dev/null
    kill_success=$?
    rm -f ${ANODE_LOCK} 2> /dev/null
    if [ ${kill_success} -eq 0 ]; then
      log_tail_success "anode stopped"
    else
      log_tail_failure "failed to stop anode"
    fi
  else
    log_tail_success "anode not started"
  fi
}

status() {
  log_head "Status anode: "
  if [ -f ${ANODE_LOCK} ]; then
    log_tail_success "anode started"
  else
    log_tail_failure "anode stopped"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
    exit 1
esac

exit 0
