package com.jag.asystem.astore;

public enum Counter {
  FILES_STAGED_SKIP,
  FILES_STAGED_REDO,
  FILES_STAGED_DONE,
  FILES_PROCESSED_SKIP,
  FILES_PROCESSED_REDO,
  FILES_PROCESSED_DONE,
  DATUMS_STAGED_COUNT,
  DATUMS_PROCESSED_COUNT
}