package com.jag.asystem.astore;

public enum Counter {
  PARTITIONS_STAGED_SKIP,
  PARTITIONS_STAGED_TODO,
  PARTITIONS_STAGED_REDO,
  PARTITIONS_STAGED_DONE,
  PARTITIONS_PROCESSED_SKIP,
  PARTITIONS_PROCESSED_TODO,
  PARTITIONS_PROCESSED_REDO,
  PARTITIONS_PROCESSED_DONE,
  DATUMS_STAGED_COUNT,
  DATUMS_PROCESSED_COUNT
}