name: ${project.artifactId}
channels:
- defaults
- conda-forge
- pantheon
dependencies:
- twisted=16.5.0
#- twisted_s3=0.2.2
#- twisted-mqtt=0.3.6
- autobahn=0.16.1
- klein=15.3.1
- treq=17.8.0
#- avro=1.7.6
- cycler=0.10.0
- requests=2.18.4
#- ilio=0.3.0
- dill=0.2.6
- pandas=0.20.1
- numpy=1.12.0
- scipy=0.19.0
- scikit-learn=0.18.1
- matplotlib=2.0.0
- astral=1.9.2
- pyyaml=3.12
- xmltodict=0.11.0
- pathlib2=2.3.2
- python-dateutil=2.6.1
- attrs=18.1.0
- mpmath=1.0.0
- mock=2.0.0
- pbr=4.0.4
- funcsigs=1.0.2
- pytables=3.4.4
- pyasn1=0.4.8
- pip=9.0.1
- python=2.7.11
